version: "3.9"

# Settings and configurations that are common for all containers
x-common:
  &common
  environment:
    POSTGRES_SERVER: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: ytdwnld

services:
  api:
    <<: *common
    build: .
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
    <<: *common
    image: postgres
    restart: always
