version: "3.9"

# Settings and configurations that are common for all containers
x-common:
  &common
  environment:
    POSTGRES_SERVER: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: ytdwnld

services:
  api:
    <<: *common
    build: .
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000

  postgres:
    <<: *common
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
