version: "3.9"

# Settings and configurations that are common for all containers
x-common:
  &common
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
    POSTGRES_SERVER: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: ytdwnld
    BUCKET_NAME: mybucket
    AWS_AK: 12345678
    AWS_SK: 12345678
    AWS_ENDPOINT: "http://minio:9000"

services:
  api:
    <<: *common
    build: .
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
    depends_on:
      - postgres
    ports:
      - 8000:8000

  postgres:
    <<: *common
    image: postgres
    restart: always
